### ISSUE TITLE
Cannot build when WITH_OTLP is ON

### ISSUE THREAD

**Issue by ovi-s** [open-telemetry/opentelemetry-cpp#465]
If I try to build on Visual Studio 2017 with WITH_OTLP ON, I got some errors. I will put the output below. If WITH_OTLP is OFF and in CMakeSettings.json is on false, the build is done without any problem.

**Steps to reproduce**
I cloned the master repository on my computer, I opened the folder and I tried to build (in any configuration)

**What is the expected behavior?**
Build without any problem

**What is the actual behavior?**
[CMakeError.log](https://github.com/open-telemetry/opentelemetry-cpp/files/5711963/CMakeError.log)
[CMakeOutput.log](https://github.com/open-telemetry/opentelemetry-cpp/files/5711966/CMakeOutput.log)

**Comment by maxgolov** [comment]
@ovi-s - I'll take a look. Are you cloning the repo recursively with submodules?

git 2.13
`git clone --recurse-submodules https://github.com/open-telemetry/opentelemetry-cpp`

**Comment by ovi-s** [comment]
Yes, I did.

> @ovi-s - I'll take a look. Are you cloning the repo recursively with submodules?
> 
> git 2.13
> `git clone --recurse-submodules https://github.com/open-telemetry/opentelemetry-cpp`

**Comment by maxgolov** [comment]
I think it's broken by one of the recent gRPC changes in `CMakeLists.txt` in this PR:
https://github.com/open-telemetry/opentelemetry-cpp/pull/431

@ThomsonTan 

I hit this issue while trying to build on Windows :

```C:\work\opentelemetry-cpp.build_tools>tools\build.cmd -DWITH_OTLP=ON                                                                                                                                                                         
Building with vs2019 Enterprise...
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.8.3
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.26.28806.0
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found Protobuf: optimized;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/lib/libprotobuf.lib;debug;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/debug/lib/libprotobufd.lib (found version "3.13.0")
CMake Warning at tools/vcpkg/scripts/buildsystems/vcpkg.cmake:536 (_find_package):
  By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gRPC", but
  CMake did not find one.

  Could not find a package configuration file provided by "gRPC" with any of
  the following names:

    gRPCConfig.cmake
    grpc-config.cmake

  Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
  "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:91 (find_package)
```

It used to work fine before.

@ovi-s - Would you mind rolling back to codebase before commit https://github.com/open-telemetry/opentelemetry-cpp/pull/431 , and see if the following command works for you?

```console
tools\build.cmd -DWITH_OTLP=ON
```

This command uses CMake with Visual Studio project generator. No Ninja.

Meanwhile I will take a look what is wrong with Visual Studio CMake build. It used to work well with Visual Studio 2019 a week ago, with OTLP exporter on.

**Comment by ThomsonTan** [comment]
@maxgolov , for your failure seems it is missing gRPC installation from vcpkg, so you'll need rerun the setup script.

For the original error, I think it is expected CMake failure that `pthread.h` cannot be found on Windows, and perhaps that is not the root cause because there is no `required` on `find_package(Threads)`. @ovi-s could you please also share the console output of cmake run?

**Comment by maxgolov** [comment]
@ThomsonTan - yes, you are right.

@ovi-s - could you please try the following:
- edit `CMakeLists.txt` to change the default to `WITH_OTLP=ON`
- try building in command line using `tools\build.cmd` script - this will build CMake - to - MSBuild project, then using MSBuild without Ninja. This is to rule out any differences in the two build systems.]

**Comment by ThomsonTan** [comment]
@ovi-s could you help check whether https://github.com/open-telemetry/opentelemetry-cpp/pull/467 fixes your build issue?

**Comment by ovi-s** [comment]
> @ovi-s could you help check whether #467 fixes your build issue?
Unfortunately it doesn't work

**Comment by lalitb** [comment]
@ovi-s Just to be sure, did you run the setup script (`.\tools\setup-buildtools.cmd`) before trying build.

**Comment by ThomsonTan** [comment]
`.\tools\setup-buildtools.cmd` should be invoked automatically during CMake configure process. Yes, please share your CMake command line and all the console output if possible. Also make sure you checked out https://github.com/open-telemetry/opentelemetry-cpp/pull/467.

**Comment by maxgolov** [comment]
One important addition: `setup-buildtools.cmd` installs things, and may need admin permissions for the first time. If using Visual Studio, you can run it as Administrator. Specific actions in there may invoke `vcpkg install` which itself may need tooling that might be missing. This machine setup step is generally done once from elevated shell, then the rest can be done from usual session in Visual Studio.

**Comment by maxgolov** [comment]
@ovi-s - I see you use Visual Studio 2017, do you have an option to upgrade and try Visual Studio 2019 IDE? Visual Studio 2019 can be configured to use any older compiler (vs2015, vs2017). And I do not currently have Visual Studio 2017 IDE installed. 

When I try building the SDK after running `setup-buildtools.cmd`, everything is compiling successfully.

CMake configure step from my system:

```console
1> CMake generation started for configuration: 'stdlib-x64-Debug'.
1> Found and using vcpkg toolchain file (C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> Command line: "cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\work\opentelemetry-cpp.build_tools\out\vs2019\stdlib-x64-Debug\install" -DWITH_STL:BOOL="True" -DWITH_OTLP:BOOL="True" -DWITH_EXAMPLES:BOOL="true" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\work\opentelemetry-cpp.build_tools" 2>&1"
1> Working directory: C:\work\opentelemetry-cpp.build_tools\out\vs2019\stdlib-x64-Debug
1> [CMake] -- The C compiler identification is MSVC 19.28.29335.0
1> [CMake] -- The CXX compiler identification is MSVC 19.28.29335.0
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Looking for pthread.h
1> [CMake] -- Looking for pthread.h - not found
1> [CMake] -- Found Threads: TRUE  
1> [CMake] -- Found Protobuf: optimized;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/lib/libprotobuf.lib;debug;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/debug/lib/libprotobufd.lib (found version "3.13.0") 
1> [CMake] -- Found ZLIB: optimized;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11") 
1> [CMake] -- Found OpenSSL: C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib (found version "1.1.1h")  
1> [CMake] -- Found c-ares: C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/share/c-ares/c-ares-config.cmake (found version "1.15.0") 
1> [CMake] PROTOBUF_PROTOC_EXECUTABLE=C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
1> [CMake] -- Found GTest: C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/lib/gtest.lib  
1> [CMake] GTEST_INCLUDE_DIRS   = C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/include
1> [CMake] GTEST_BOTH_LIBRARIES = optimized;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/lib/gtest.lib;debug;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/debug/lib/gtestd.lib;optimized;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/lib/manual-link/gtest_main.lib;debug;C:/work/opentelemetry-cpp.build_tools/tools/vcpkg/installed/x64-windows/debug/lib/manual-link/gtest_maind.lib
1> [CMake] Building with standard library types...
1> [CMake] -- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: C:/work/opentelemetry-cpp.build_tools/out/vs2019/stdlib-x64-Debug
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted includes paths.
1> CMake generation finished.
```

CMake build from my system (built with Ninja, for Debug):
```console
...
  [193/193] Linking CXX executable examples\otlp\example_otlp.exe

Build All succeeded.
```

🤔

I am not sure if maybe there's a bug in Visual Studio 2017 built-in CMake support. But 2019 works fine.

**Comment by maxgolov** [comment]
@ThomsonTan - do we need your fix merged to resolve the issue when the dependencies have not been pre-installed with `setup-buildtools.cmd` ? https://github.com/open-telemetry/opentelemetry-cpp/pull/467

**Comment by ThomsonTan** [comment]
@maxgolov - I think we need merge https://github.com/open-telemetry/opentelemetry-cpp/pull/467 to resolve the missing dependency installations by `setup-buildtools.cmd`. But @ovi-s said the PR didn't fix the issue in this thread, I am wondering what is missing here.

**Comment by maxgolov** [comment]
@ovi-s - is there a chance you can try Visual Studio 2019? It works for me with vs2019 IDE. I can't repro the issue. Even community edition should work.

**Comment by ovi-s** [comment]
I need to use Visual Studio 2017 Professional, as this is the official tool at work. I will modify vcvars.cmd to accept also VS2017 Professional and I will try another build

**Comment by alolita** [comment]
@ovi-s can you provide more info about your CLI output?

**Comment by maxgolov** [comment]
@ovi-s - I only tested in vs2019 (works CMake+ninja); and vs2017 build tools (works for CMake+MSBuild generated project in command line). I do not have vs2017 full IDE installed. But I will install one and give it a try to see if I can repro your scenario.. Does it all compile for you in command line if you use `tools/build.cmd` script?

**Comment by lalitb** [comment]
@maxgolov We can close this if it is not reproducible, as we don't see any further comments from @ovi-s

**Comment by ovi-s** [comment]
Sorry guys, I did not have time to check again. I will do it no later than next week.

**Comment by ovi-s** [comment]
I cloned today again the project and now is working

**Comment by maxgolov** [comment]
We can contribute a write-up for Visual Studio 2019. Building whatever multiple configurations with CMake works well with 2019, including configuration with OTLP ON. I noticed a few differences between vs2019 and vs2017. And at this time it'd be kinda "hard" (no time) to contribute a similar write-up for an older version of Visual Studio 2017...

We can say that we still support command line builds for 2017, and we still support generating MSBuild solution using that (placed in the `out` directory) which then can be opened in Visual Studio 2017 IDE. One minor issue with that MSBuild gen approach, that every time CMakeLists.txt changes - the project will get regenerated.
